#spring:
#  application:
#    name: ${APPLICATION_NAME:gateway}
#  #  profiles:
#  #    active: ${PROFILE_ACTIVE:dev}
#  cloud:
#    nacos:
#      discovery:
#        #id:端口号
#        server-addr: ${NACOS_SERVER:192.168.101.129:8848}
#        #命名空间
#        namespace: ${NACOS_NAMESPACE:public}
#      config:
#        #        import-check:
#        #          enabled: false
#        #id:端口号
#        server-addr: ${NACOS_SERVER:192.168.101.129:8848}
#        #命名空间
#        namespace: ${NACOS_NAMESPACE:public}
#        #配置文件格式
#        file-extension: yaml
#      #username
#      username: nacos
#      #password
#      password: Zhi@13579,qAZ
#    gateway:
#      discovery:
#        locator: #开启从注册中心动态创建路由的功能，利用微服务名进行路由
#          enabled: true
#          #开启小写验证，默认feign根据服务名查找都是用的全大写
#          lowerCaseServiceId: true
